FROM php:7.4-fpm

#COPY ./common/php/conf.d /usr/local/etc/php/conf.d
#COPY ./development/php/conf.d /usr/local/etc/php/conf.d
#COPY ./development/php-fpm/conf.d /usr/local/etc/php/conf.d

WORKDIR /app